### ISSUE TITLE
/root directory in `ffb-91.0`

### ISSUE THREAD

**Issue by dm9pZCAq** [kiss-community/bin#1]
kiss installs `/root/.cache/kiss/proc/2949/build/...`

**Comment by dilyn-corner** [comment]
Will fix shortly :)

**Comment by dilyn-corner** [comment]
Fixed! cc6c8b31a30b7450f2064a18c8e36cb7c659c100

**Comment by dm9pZCAq** [comment]
btw, there will be no more builds for Xorg?

**Comment by dilyn-corner** [comment]
As I've been saying for the last few weeks, anybody who wants to maintain Xorg or libressl support in this organization is more than welcome to submit a request to join and do that! Nobody has so far expressed any interest in doing so and have instead opted to create their own repositories (which is totally fine). I haven't been using Xorg for quite some time and have no interest in providing support for it, and I don't intend on providing binaries that don't follow what Dylan does with KISS; I will continue to use whatever chroots and repositories he uploads to make these packages. 

If someone wanted to contribute Xorg binaries here, I would have no problem with that; but there would need to be good support in this org to do so. That is to say, I would only really want to see a `firefox` that requires Xorg if there were a Xorg repository here.
