### ISSUE TITLE
How do I contribute?

### ISSUE THREAD

**Issue by fluorescent-haze** [kiss-community/bin#2]
I'd like to contribute my binary packages, but I don't know how. It seems I wouldn't be able to just do a pull request, as all the packages are releases. Or do you not accept binary packages outside of KISS Community members, which would also make sense. Thanks!

**Comment by git-bruh** [comment]
Hi, sorry for the late reply

I think we could make it such that contributors just fork the repository, upload binaries to their fork and submit PRs with binary links pointing to the fork's release. 

Welcome to any other suggestions.

**Comment by fluorescent-haze** [comment]
> I think we could make it such that contributors just fork the repository, upload binaries to their fork and submit PRs with binary links pointing to the fork's release.

That sounds like a fine way to go; I'll do that, thanks! Closing this issue.
